#!/bin/bash


cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

cd /tmp
time rclone copy /tmp/rom/out/target/product/onclite/Nusantara*.zip MyDrive:onclite -P
cd /tmp
time rclone copy ccache.tar.gz MyDrive:nusantara -P
