#!/bin/bash

cd /tmp/rom

repo init -q --no-repo-verify --depth=1 -u https://github.com/NusantaraProject-ROM/android_manifest -b 11 -g default,-device,-mips,-darwin,-notdefault
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

# DT/VT/KT
git clone https://github.com/NusantaraROM-Devices/device_xiaomi_onclite -b 11 device/xiaomi/onclite
git clone --depth=1 https://github.com/NusantaraROM-Devices/vendor_xiaomi_onclite --single-branch -b 11 vendor/xiaomi/onclite
git clone --depth=1 https://github.com/NusantaraROM-Devices/kernel_xiaomi_onclite --single-branch -b 11 kernel/xiaomi/onclite

# TOOLCHAIN
git clone --depth=1 https://github.com/kdrag0n/proton-clang --single-branch -b master prebuilts/clang/host/linux-x86/clang-proton

#HALS
rm -rf hardware/qcom-caf/msm8953/audio
rm -rf hardware/qcom-caf/msm8953/display
rm -rf hardware/qcom-caf/msm8953/media
git clone --depth=1 https://github.com/JarlPenguin/platform_hardware_qcom_msm8953_audio hardware/qcom-caf/msm8953/audio
git clone --depth=1 https://github.com/JarlPenguin/platform_hardware_qcom_msm8953_display hardware/qcom-caf/msm8953/display
git clone --depth=1 https://github.com/JarlPenguin/platform_hardware_qcom_msm8953_media hardware/qcom-caf/msm8953/media
